#!/bin/bash

# Unduh dan salin file fw ke /usr/local/bin
curl -o /home/.local/bin/fw -sL https://raw.githubusercontent.com/salmanelparl/fw/main/fw

# Berikan izin eksekusi pada file fw
chmod +x /home/.local/bin/fw

echo "Installation complete. You can run 'fw' now."

# Memeriksa apakah argumen telah diberikan
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 username/repository"
    exit 1
fi

# Mendapatkan argumen
REPO=$1

# Mengambil nama repository dari argumen
REPO_NAME=$(basename "$REPO")

# Membuat direktori framework jika belum ada
mkdir -p framework

# Menghapus direktori repository jika ada
rm -rf "framework/$REPO_NAME"

# Mengkloning repositori ke dalam direktori yang sesuai dengan nama repositori
git clone --recurse-submodules "https://github.com/$REPO.git" "framework/$REPO_NAME"

# Menampilkan pesan selesai
echo "Instalasi selesai. Repositori $REPO telah dikloning ke framework/$REPO_NAME."
